name: Potato Kernel Alioth
run-name: Potato Kernel Alioth

on:
  push:
    branches: [ staging ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu

    steps:
      - uses: actions/checkout@v3
      - name: Build Kernel Alioth
        run: apt update -y && apt install -y build-essential libncurses-dev bison flex libssl-dev bc gcc git make ccache rsync python3 python3-distutils dwarves curl sudo && bash clone.sh && cd kernel/ && bash kbuild.sh alioth null
        env:
           token: ${{ secrets.TOKEN }}
           chat_id: ${{ secrets.CHAT_ID }}
